gvquest_streaks.settings:
  type: config_object
  label: 'GVQuest streaks settings'
  mapping:
    daily_target_type:
      type: string
      label: 'Default target type'
    daily_target_value:
      type: float
      label: 'Default target value'
    grace_days:
      type: integer
      label: 'Grace days'
    timezone:
      type: string
      label: 'Default timezone'
    start_date:
      type: string
      label: 'Default start date'
    email_reminder_enabled:
      type: boolean
      label: 'Enable reminder emails'
    email_reminder_time:
      type: string
      label: 'Reminder time'

streak_rule.*:
  type: config_entity
  label: 'Streak rule'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    user_id:
      type: integer
      label: 'User ID'
    daily_target_type:
      type: string
      label: 'Target type'
    daily_target_value:
      type: float
      label: 'Target value'
    grace_days:
      type: integer
      label: 'Grace days'
    timezone:
      type: string
      label: 'Timezone'
    start_date:
      type: string
      label: 'Start date'
    active:
      type: boolean
      label: 'Active'
