name: ddev-gvbooks
networks:
    ddev_default:
        external: true
        name: ddev_default
    default:
        labels:
            com.ddev.platform: ddev
        name: ddev-gvbooks_default
services:
    db:
        build:
            args:
                BASE_IMAGE: ddev/ddev-dbserver-mariadb-10.11:20250213_rfay_mariadb_11.8
                gid: "20"
                uid: "501"
                username: giangvincent
            context: /Users/giangvincent/Documents/drupal/GvBooks/.ddev/.dbimageBuild
            dockerfile: Dockerfile
        cap_add:
            - SYS_NICE
        command: []
        container_name: ddev-gvbooks-db
        environment:
            BITNAMI_VOLUME_DIR: ""
            COLUMNS: "206"
            DDEV_DATABASE: mariadb:10.11
            DDEV_DATABASE_FAMILY: mysql
            DDEV_GID: "20"
            DDEV_GOARCH: arm64
            DDEV_GOOS: darwin
            DDEV_HOSTNAME: gvbooks.ddev.site
            DDEV_PHP_VERSION: "8.3"
            DDEV_PRIMARY_URL: https://gvbooks.ddev.site
            DDEV_PRIMARY_URL_PORT: "443"
            DDEV_PRIMARY_URL_WITHOUT_PORT: https://gvbooks.ddev.site
            DDEV_PROJECT: gvbooks
            DDEV_PROJECT_TYPE: drupal10
            DDEV_ROUTER_HTTP_PORT: "33001"
            DDEV_ROUTER_HTTPS_PORT: "443"
            DDEV_SCHEME: https
            DDEV_SITENAME: gvbooks
            DDEV_TLD: ddev.site
            DDEV_UID: "501"
            DDEV_USER: giangvincent
            DDEV_VERSION: v1.24.6-54-gbaf023e54
            DOCKER_IP: 127.0.0.1
            HOST_DOCKER_INTERNAL_IP: ""
            IS_DDEV_PROJECT: "true"
            LINES: "25"
            MYSQL_HISTFILE: /mnt/ddev-global-cache/mysqlhistory/gvbooks-db/mysql_history
            PGDATABASE: db
            PGHOST: 127.0.0.1
            PGPASSWORD: db
            PGUSER: db
            POSTGRES_DB: db
            POSTGRES_PASSWORD: db
            POSTGRES_USER: db
            TZ: Asia/Ho_Chi_Minh
            USER: giangvincent
        healthcheck:
            interval: 1s
            retries: 70
            start_interval: 1s
            start_period: 2m0s
            timeout: 1m10s
        hostname: gvbooks-db
        image: ddev/ddev-dbserver-mariadb-10.11:20250213_rfay_mariadb_11.8-gvbooks-built
        labels:
            com.ddev.app-type: drupal10
            com.ddev.approot: /Users/giangvincent/Documents/drupal/GvBooks
            com.ddev.platform: ddev
            com.ddev.site-name: gvbooks
        networks:
            ddev_default: null
            default: null
        ports:
            - host_ip: 127.0.0.1
              mode: ingress
              protocol: tcp
              target: 3306
        restart: "no"
        stop_grace_period: 1m0s
        user: "501:20"
        volumes:
            - source: database
              target: /var/lib/mysql
              type: volume
              volume:
                nocopy: true
            - bind:
                create_host_path: true
              source: /Users/giangvincent/Documents/drupal/GvBooks/.ddev
              target: /mnt/ddev_config
              type: bind
            - bind:
                create_host_path: true
              source: /Users/giangvincent/Documents/drupal/GvBooks/.ddev/db_snapshots
              target: /mnt/snapshots
              type: bind
            - source: ddev-global-cache
              target: /mnt/ddev-global-cache
              type: volume
              volume: {}
        working_dir: /home/giangvincent
    phpmyadmin:
        container_name: ddev-gvbooks-phpmyadmin
        depends_on:
            db:
                condition: service_started
                required: true
        environment:
            HTTP_EXPOSE: 8036:80
            HTTPS_EXPOSE: 8037:80
            PMA_HOST: db
            PMA_PASSWORD: root
            PMA_PORT: "3306"
            PMA_USER: root
            UPLOAD_LIMIT: 4000M
            VIRTUAL_HOST: gvbooks.ddev.site
        expose:
            - "80"
        healthcheck:
            interval: 2m0s
            retries: 1
            timeout: 2s
        image: phpmyadmin:5.2.0
        labels:
            com.ddev.approot: /Users/giangvincent/Documents/drupal/GvBooks
            com.ddev.site-name: gvbooks
        networks:
            ddev_default: null
            default: null
        restart: "no"
        volumes:
            - bind:
                create_host_path: true
              source: /Users/giangvincent/Documents/drupal/GvBooks/.ddev
              target: /mnt/ddev_config
              type: bind
            - source: ddev-global-cache
              target: /mnt/ddev-global-cache
              type: volume
              volume: {}
        working_dir: /root
    web:
        build:
            args:
                BASE_IMAGE: ddev/ddev-webserver:20250612_stasadev_rebuild_images
                DDEV_DATABASE: mariadb:10.11
                DDEV_PHP_VERSION: "8.3"
                gid: "20"
                uid: "501"
                username: giangvincent
            context: /Users/giangvincent/Documents/drupal/GvBooks/.ddev/.webimageBuild
            dockerfile: Dockerfile
        cap_add:
            - SYS_PTRACE
        command:
            - /pre-start.sh
        container_name: ddev-gvbooks-web
        environment:
            COLUMNS: "206"
            COREPACK_ENABLE_DOWNLOAD_PROMPT: "0"
            COREPACK_HOME: /mnt/ddev-global-cache/corepack
            DDEV_APPROOT: /var/www/html
            DDEV_COMPOSER_ROOT: /var/www/html
            DDEV_DATABASE: mariadb:10.11
            DDEV_DATABASE_FAMILY: mysql
            DDEV_DOCROOT: web
            DDEV_FILES_DIR: /var/www/html/web/sites/default/files
            DDEV_FILES_DIRS: /var/www/html/web/sites/default/files
            DDEV_GID: "20"
            DDEV_GOARCH: arm64
            DDEV_GOOS: darwin
            DDEV_HOSTNAME: gvbooks.ddev.site
            DDEV_MUTAGEN_ENABLED: "true"
            DDEV_PHP_VERSION: "8.3"
            DDEV_PRIMARY_URL: https://gvbooks.ddev.site
            DDEV_PRIMARY_URL_PORT: "443"
            DDEV_PRIMARY_URL_WITHOUT_PORT: https://gvbooks.ddev.site
            DDEV_PROJECT: gvbooks
            DDEV_PROJECT_TYPE: drupal10
            DDEV_ROUTER_HTTP_PORT: "33001"
            DDEV_ROUTER_HTTPS_PORT: "443"
            DDEV_SCHEME: https
            DDEV_SITENAME: gvbooks
            DDEV_TLD: ddev.site
            DDEV_UID: "501"
            DDEV_USER: giangvincent
            DDEV_VERSION: v1.24.6-54-gbaf023e54
            DDEV_WEB_ENTRYPOINT: /mnt/ddev_config/web-entrypoint.d
            DDEV_WEBSERVER_TYPE: nginx-fpm
            DDEV_XDEBUG_ENABLED: "false"
            DDEV_XHPROF_MODE: prepend
            DEPLOY_NAME: local
            DOCKER_IP: 127.0.0.1
            DOCROOT: web
            DRUSH_OPTIONS_URI: https://gvbooks.ddev.site
            HOST_DOCKER_INTERNAL_IP: ""
            HTTP_EXPOSE: 33001:80,8025:8025
            HTTPS_EXPOSE: 443:80,8026:8025
            IS_DDEV_PROJECT: "true"
            LINES: "25"
            MYSQL_HISTFILE: /mnt/ddev-global-cache/mysqlhistory/gvbooks-web/mysql_history
            NODE_EXTRA_CA_CERTS: /mnt/ddev-global-cache/mkcert/rootCA.pem
            PGDATABASE: db
            PGHOST: db
            PGPASSWORD: db
            PGUSER: db
            PHP_IDE_CONFIG: serverName=gvbooks.ddev.site
            SSH_AUTH_SOCK: /home/.ssh-agent/socket
            START_SCRIPT_TIMEOUT: "30"
            TZ: Asia/Ho_Chi_Minh
            USER: giangvincent
            VIRTUAL_HOST: gvbooks.ddev.site
            npm_config_cache: /mnt/ddev-global-cache/npm
        external_links:
            - ddev-router:gvbooks.ddev.site
        healthcheck:
            interval: 1s
            retries: 70
            start_interval: 1s
            start_period: 2m0s
            timeout: 1m10s
        hostname: gvbooks-web
        image: ddev/ddev-webserver:20250612_stasadev_rebuild_images-gvbooks-built
        labels:
            com.ddev.app-type: drupal10
            com.ddev.approot: /Users/giangvincent/Documents/drupal/GvBooks
            com.ddev.platform: ddev
            com.ddev.site-name: gvbooks
        networks:
            ddev_default: null
            default: null
        ports:
            - host_ip: 127.0.0.1
              mode: ingress
              protocol: tcp
              target: 80
            - host_ip: 127.0.0.1
              mode: ingress
              protocol: tcp
              target: 443
            - host_ip: 127.0.0.1
              mode: ingress
              protocol: tcp
              target: 8025
        restart: "no"
        user: "501:20"
        volumes:
            - source: project_mutagen
              target: /var/www
              type: volume
              volume:
                nocopy: true
            - source: project_mutagen
              target: /tmp/project_mutagen
              type: volume
              volume:
                nocopy: true
            - bind:
                create_host_path: true
              read_only: true
              source: /Users/giangvincent/Documents/drupal/GvBooks/.ddev
              target: /mnt/ddev_config
              type: bind
            - bind:
                create_host_path: true
              source: /Users/giangvincent/Documents/drupal/GvBooks/.ddev/xhprof
              target: /usr/local/bin/xhprof
              type: bind
            - bind:
                create_host_path: true
              source: /Users/giangvincent/Documents/drupal/GvBooks/web/sites/default/files
              target: /var/www/html/web/sites/default/files
              type: bind
            - bind:
                create_host_path: true
              source: /Users/giangvincent/Documents/drupal/GvBooks/.git
              target: /var/www/html/.git
              type: bind
            - source: ddev-global-cache
              target: /mnt/ddev-global-cache
              type: volume
              volume: {}
            - source: ddev-ssh-agent_socket_dir
              target: /home/.ssh-agent
              type: volume
              volume: {}
        working_dir: /var/www/html/
    xhgui:
        container_name: ddev-gvbooks-xhgui
        depends_on:
            db:
                condition: service_started
                required: true
        environment:
            DDEV_DATABASE_FAMILY: mysql
            HTTP_EXPOSE: 8143:80
            HTTPS_EXPOSE: 8142:80
            TZ: Asia/Ho_Chi_Minh
            VIRTUAL_HOST: gvbooks.ddev.site
            XHGUI_PDO_PASS: db
            XHGUI_PDO_USER: db
            XHGUI_SAVE_HANDLER: pdo
        image: ddev/ddev-xhgui:v1.24.6
        labels:
            com.ddev.approot: /Users/giangvincent/Documents/drupal/GvBooks
            com.ddev.site-name: gvbooks
        links:
            - db
        networks:
            ddev_default: null
            default: null
        profiles:
            - xhgui
        restart: "no"
volumes:
    database:
        external: true
        name: gvbooks-mariadb
    ddev-global-cache:
        external: true
        name: ddev-global-cache
    ddev-ssh-agent_socket_dir:
        external: true
        name: ddev-ssh-agent_socket_dir
    project_mutagen:
        external: true
        name: gvbooks_project_mutagen
