name: ddev-gvbooks
services:
  db:
    build:
      context: /Users/giangvincent/Documents/drupal/GvBooks/.ddev/.dbimageBuild
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ddev/ddev-dbserver-mariadb-10.11:20250824_akibaat_buildx_arm_builder
        gid: "20"
        uid: "501"
        username: giangvincent
    cap_add:
      - SYS_NICE
    command: []
    container_name: ddev-gvbooks-db
    environment:
      BITNAMI_VOLUME_DIR: ""
      COLUMNS: "171"
      DDEV_DATABASE: mariadb:10.11
      DDEV_DATABASE_FAMILY: mysql
      DDEV_GID: "20"
      DDEV_GOARCH: arm64
      DDEV_GOOS: darwin
      DDEV_HOSTNAME: gvbooks.ddev.site
      DDEV_PHP_VERSION: "8.3"
      DDEV_PRIMARY_URL: https://gvbooks.ddev.site
      DDEV_PRIMARY_URL_PORT: "443"
      DDEV_PRIMARY_URL_WITHOUT_PORT: https://gvbooks.ddev.site
      DDEV_PROJECT: gvbooks
      DDEV_PROJECT_TYPE: drupal10
      DDEV_ROUTER_HTTP_PORT: "33002"
      DDEV_ROUTER_HTTPS_PORT: "443"
      DDEV_SCHEME: https
      DDEV_SITENAME: gvbooks
      DDEV_TLD: ddev.site
      DDEV_UID: "501"
      DDEV_USER: giangvincent
      DDEV_VERSION: v1.24.8-30-gce29c53d5
      DOCKER_IP: 127.0.0.1
      HOST_DOCKER_INTERNAL_IP: ""
      IS_DDEV_PROJECT: "true"
      LINES: "25"
      MYSQL_HISTFILE: /mnt/ddev-global-cache/mysqlhistory/gvbooks-db/mysql_history
      PGDATABASE: db
      PGHOST: 127.0.0.1
      PGPASSWORD: db
      PGUSER: db
      POSTGRES_DB: db
      POSTGRES_PASSWORD: db
      POSTGRES_USER: db
      TZ: Asia/Ho_Chi_Minh
      USER: giangvincent
    hostname: gvbooks-db
    healthcheck:
      timeout: 1m10s
      interval: 1s
      retries: 70
      start_period: 2m0s
      start_interval: 1s
    image: ddev/ddev-dbserver-mariadb-10.11:20250824_akibaat_buildx_arm_builder-gvbooks-built
    labels:
      com.ddev.app-type: drupal10
      com.ddev.approot: /Users/giangvincent/Documents/drupal/GvBooks
      com.ddev.platform: ddev
      com.ddev.site-name: gvbooks
    networks:
      ddev_default: null
      default: null
    ports:
      - mode: ingress
        host_ip: 127.0.0.1
        target: 3306
        protocol: tcp
    restart: "no"
    stop_grace_period: 1m0s
    user: "501:20"
    volumes:
      - type: volume
        source: database
        target: /var/lib/mysql
        volume:
          nocopy: true
      - type: bind
        source: /Users/giangvincent/Documents/drupal/GvBooks/.ddev
        target: /mnt/ddev_config
        bind:
          create_host_path: true
      - type: bind
        source: /Users/giangvincent/Documents/drupal/GvBooks/.ddev/db_snapshots
        target: /mnt/snapshots
        bind:
          create_host_path: true
      - type: volume
        source: ddev-global-cache
        target: /mnt/ddev-global-cache
        volume: {}
    working_dir: /home/giangvincent
  phpmyadmin:
    container_name: ddev-gvbooks-phpmyadmin
    depends_on:
      db:
        condition: service_started
        required: true
    environment:
      HOST_DOCKER_INTERNAL_IP: ""
      HTTP_EXPOSE: 8036:80
      HTTPS_EXPOSE: 8037:80
      PMA_HOST: db
      PMA_PASSWORD: root
      PMA_PORT: "3306"
      PMA_USER: root
      UPLOAD_LIMIT: 4000M
      VIRTUAL_HOST: gvbooks.ddev.site
    expose:
      - "80"
    healthcheck:
      timeout: 2s
      interval: 2m0s
      retries: 1
    image: phpmyadmin:5.2.0
    labels:
      com.ddev.approot: /Users/giangvincent/Documents/drupal/GvBooks
      com.ddev.site-name: gvbooks
    networks:
      ddev_default: null
      default: null
    restart: "no"
    volumes:
      - type: bind
        source: /Users/giangvincent/Documents/drupal/GvBooks/.ddev
        target: /mnt/ddev_config
        bind:
          create_host_path: true
      - type: volume
        source: ddev-global-cache
        target: /mnt/ddev-global-cache
        volume: {}
    working_dir: /root
  web:
    build:
      context: /Users/giangvincent/Documents/drupal/GvBooks/.ddev/.webimageBuild
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ddev/ddev-webserver:20250824_akibaat_buildx_arm_builder
        DDEV_DATABASE: mariadb:10.11
        DDEV_PHP_VERSION: "8.3"
        gid: "20"
        uid: "501"
        username: giangvincent
    cap_add:
      - SYS_PTRACE
    command:
      - /pre-start.sh
    container_name: ddev-gvbooks-web
    environment:
      COLUMNS: "171"
      COREPACK_ENABLE_DOWNLOAD_PROMPT: "0"
      COREPACK_HOME: /mnt/ddev-global-cache/corepack
      DDEV_APPROOT: /var/www/html
      DDEV_COMPOSER_ROOT: /var/www/html
      DDEV_DATABASE: mariadb:10.11
      DDEV_DATABASE_FAMILY: mysql
      DDEV_DOCROOT: web
      DDEV_FILES_DIR: /var/www/html/web/sites/default/files
      DDEV_FILES_DIRS: /var/www/html/web/sites/default/files
      DDEV_GID: "20"
      DDEV_GOARCH: arm64
      DDEV_GOOS: darwin
      DDEV_HOSTNAME: gvbooks.ddev.site
      DDEV_MUTAGEN_ENABLED: "true"
      DDEV_PHP_VERSION: "8.3"
      DDEV_PRIMARY_URL: https://gvbooks.ddev.site
      DDEV_PRIMARY_URL_PORT: "443"
      DDEV_PRIMARY_URL_WITHOUT_PORT: https://gvbooks.ddev.site
      DDEV_PROJECT: gvbooks
      DDEV_PROJECT_TYPE: drupal10
      DDEV_ROUTER_HTTP_PORT: "33002"
      DDEV_ROUTER_HTTPS_PORT: "443"
      DDEV_SCHEME: https
      DDEV_SITENAME: gvbooks
      DDEV_TLD: ddev.site
      DDEV_UID: "501"
      DDEV_USER: giangvincent
      DDEV_VERSION: v1.24.8-30-gce29c53d5
      DDEV_WEB_ENTRYPOINT: /mnt/ddev_config/web-entrypoint.d
      DDEV_WEBSERVER_TYPE: nginx-fpm
      DDEV_XDEBUG_ENABLED: "false"
      DDEV_XHPROF_MODE: prepend
      DEPLOY_NAME: local
      DOCKER_IP: 127.0.0.1
      DOCROOT: web
      DRUSH_OPTIONS_URI: https://gvbooks.ddev.site
      HOST_DOCKER_INTERNAL_IP: ""
      HTTP_EXPOSE: 33002:80,8025:8025
      HTTPS_EXPOSE: 443:80,8026:8025
      IS_DDEV_PROJECT: "true"
      LINES: "25"
      MYSQL_HISTFILE: /mnt/ddev-global-cache/mysqlhistory/gvbooks-web/mysql_history
      NODE_EXTRA_CA_CERTS: /mnt/ddev-global-cache/mkcert/rootCA.pem
      PGDATABASE: db
      PGHOST: db
      PGPASSWORD: db
      PGUSER: db
      PHP_IDE_CONFIG: serverName=gvbooks.ddev.site
      SSH_AUTH_SOCK: /home/.ssh-agent/socket
      START_SCRIPT_TIMEOUT: "57"
      TZ: Asia/Ho_Chi_Minh
      USER: giangvincent
      VIRTUAL_HOST: gvbooks.ddev.site
      npm_config_cache: /mnt/ddev-global-cache/npm
    hostname: gvbooks-web
    healthcheck:
      timeout: 1m10s
      interval: 1s
      retries: 70
      start_period: 2m0s
      start_interval: 1s
    image: ddev/ddev-webserver:20250824_akibaat_buildx_arm_builder-gvbooks-built
    labels:
      com.ddev.app-type: drupal10
      com.ddev.approot: /Users/giangvincent/Documents/drupal/GvBooks
      com.ddev.platform: ddev
      com.ddev.site-name: gvbooks
    networks:
      ddev_default: null
      default: null
    ports:
      - mode: ingress
        host_ip: 127.0.0.1
        target: 80
        protocol: tcp
      - mode: ingress
        host_ip: 127.0.0.1
        target: 443
        protocol: tcp
      - mode: ingress
        host_ip: 127.0.0.1
        target: 8025
        protocol: tcp
    restart: "no"
    user: "501:20"
    volumes:
      - type: volume
        source: project_mutagen
        target: /var/www
        volume:
          nocopy: true
      - type: volume
        source: project_mutagen
        target: /tmp/project_mutagen
        volume:
          nocopy: true
      - type: bind
        source: /Users/giangvincent/Documents/drupal/GvBooks/.ddev
        target: /mnt/ddev_config
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: /Users/giangvincent/Documents/drupal/GvBooks/.ddev/xhprof
        target: /usr/local/bin/xhprof
        bind:
          create_host_path: true
      - type: bind
        source: /Users/giangvincent/Documents/drupal/GvBooks/web/sites/default/files
        target: /var/www/html/web/sites/default/files
        bind:
          create_host_path: true
      - type: bind
        source: /Users/giangvincent/Documents/drupal/GvBooks/.git
        target: /var/www/html/.git
        bind:
          create_host_path: true
      - type: volume
        source: ddev-global-cache
        target: /mnt/ddev-global-cache
        volume: {}
      - type: volume
        source: ddev-ssh-agent_socket_dir
        target: /home/.ssh-agent
        volume: {}
    working_dir: /var/www/html/
  xhgui:
    profiles:
      - xhgui
    container_name: ddev-gvbooks-xhgui
    depends_on:
      db:
        condition: service_started
        required: true
    environment:
      DDEV_DATABASE_FAMILY: mysql
      HOST_DOCKER_INTERNAL_IP: ""
      HTTP_EXPOSE: 8143:80
      HTTPS_EXPOSE: 8142:80
      TZ: Asia/Ho_Chi_Minh
      VIRTUAL_HOST: gvbooks.ddev.site
      XHGUI_PDO_PASS: db
      XHGUI_PDO_USER: db
      XHGUI_SAVE_HANDLER: pdo
    image: ddev/ddev-xhgui:20250824_akibaat_buildx_arm_builder
    labels:
      com.ddev.approot: /Users/giangvincent/Documents/drupal/GvBooks
      com.ddev.site-name: gvbooks
    networks:
      ddev_default: null
      default: null
    restart: "no"
networks:
  ddev_default:
    name: ddev_default
    external: true
  default:
    name: ddev-gvbooks_default
    labels:
      com.ddev.platform: ddev
volumes:
  database:
    name: gvbooks-mariadb
    external: true
  ddev-global-cache:
    name: ddev-global-cache
    external: true
  ddev-ssh-agent_socket_dir:
    name: ddev-ssh-agent_socket_dir
    external: true
  project_mutagen:
    name: gvbooks_project_mutagen
    external: true
