name: gvbooks
type: drupal10
docroot: web
php_version: "8.2"
webserver_type: nginx-fpm
router_http_port: "8080"
router_https_port: "8443"
router_bind_all_interfaces: false
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
use_dns_when_possible: true
timezone: ""
composer_version: ""
web_environment: []
